# Generated by Cloud66 Starter
FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y build-essential nodejs

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN gem install bundler:2.1.2
ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME
RUN RAILS_ENV=production bundle exec rails assets:precompile
