web:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ADDRESS: db
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: 'true'
    RAILS_LOG_TO_STDOUT: 'true'
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root

